### ISSUE TITLE
Improve documentation of Stackoverflow_Survey_Analysis.ipynb 2018 Dataset ( Part 1 )

### ISSUE THREAD

**Issue by tech-hardik** [Recode-Hive/Stackoverflow-Analysis#102]
**Describe the bug**
Comments explaining the code are currently too short and not present in some places well.

**Expected behavior**
Increasing frequency of comments and explaining the code more while learning about the code as well.

**Curent Goal in Part 1**
Reaching till half of 2018 Dataset and improving the comments as much as possible.

Kindly label the issue and assign it to me :)
Very excited for my first contribution.

**Comment by tech-hardik** [comment]
kindly assign me the issue :)

**Comment by okaditya84** [comment]
> **Describe the bug** Comments explaining the code are currently too short and not present in some places well.
> 
> **Expected behavior** Increasing frequency of comments and explaining the code more while learning about the code as well.
> 
> **Curent Goal in Part 1** Reaching till half of 2018 Dataset and improving the comments as much as possible.
> 
> Kindly label the issue and assign it to me :) Very excited for my first contribution.

I see your point but describe more on how will you add more details without affecting the code readability and organization.

**Comment by sanjay-kv** [comment]
This is moved into backlog as one of the PR made different file than working on the existing file Stackoverflow_Survey_Analysis.ipynb 2018 Dataset ( Part 1 )
