### ISSUE TITLE
Create a Wiki page for the project

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#112]
**Is your feature request related to a problem? Please describe.**
Create a Wiki page for Stackoverflow Analysis: https://github.com/Recode-Hive/Stackoverflow-Analysis/wiki

**Comment by tech-hardik** [comment]
Kindly assign me this issue. Let me know what wiki pages you would like though.

I do have some ideas like there should be one page for contributors.

**Comment by sanjay-kv** [comment]
Hi, Maybe something like this then eventually we will upgrade. 

https://github.com/Netflix/Hystrix/wiki

This has more details: https://github.com/MyHoneyBadger/awesome-github-wiki 

Welcome to add your creativity as well. Lets make the best one

**Comment by tech-hardik** [comment]
Hi, I've created the basic wiki but there's a problem - GitHub doesn't have pull requests for Wiki.
Refer this thread for the issue - https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github

Let me know how I can share the wiki then. 
Also if its not as a PR request will it not be counted towards the leaderboard?

**Comment by sanjay-kv** [comment]
> Hi, I've created the basic wiki but there's a problem - GitHub doesn't have pull requests for Wiki. Refer this thread for the issue - https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github
> 
> Let me know how I can share the wiki then. Also if its not as a PR request will it not be counted towards the leaderboard?

You can add the link to wifi to readmen file and I will merge it with level2. So it will count to leaderboard.
