### ISSUE TITLE
Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [Recode-Hive/Stackoverflow-Analysis#114]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. When pull requests (PRs) are merged in a project, it is often important to provide consistent feedback or notifications to the contributors. Currently, this process can be manual and time-consuming, leading to inconsistent communication and delayed acknowledgments. This can frustrate both maintainers, who have to remember to comment, and contributors, who might feel their efforts are not promptly recognized.

**Describe the solution you'd like**
To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:
PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.

**What problem is this feature trying to solve?**
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

**Comment by Asymtode712** [comment]
@sanjay-kv please assign me this issue under gssoc'24

**Comment by sanjay-kv** [comment]
Sure, can you work on this repo as well 
https://github.com/Recode-Hive/Scrape-ML, its included in the gssoc, create a new issue I will assign to you.
