### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by Ananya54321** [Recode-Hive/Stackoverflow-Analysis#126]
**Describe the bug**
When you click on the contributor guidelines in the readme section, it redirects you to a 404 not found error

**To Reproduce**
1. Go to 'contributions'
2. Click on 'contribution guidelines'
3. See error

**Expected behavior**
Redirection to the contribution guidelines

**Screenshots**
<img width="1468" alt="Screenshot 2024-05-20 at 10 14 43 AM" src="https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/116152722/f33e4df6-ca12-4a42-8a24-ea89e4b27551">
<img width="896" alt="Screenshot 2024-05-20 at 10 13 47 AM" src="https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/116152722/8d25844c-4f7e-4034-913a-ce68765f7f52">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 124.0.6367.208

I would like to work on this issue and fix it

**Comment by sanjay-kv** [comment]
Thanks for Highlighting, you can redirect into https://github.com/Recode-Hive/Stackoverflow-Analysis/tree/main/Readme

**Comment by Ananya54321** [comment]
Hello! I opened a pull request for it! Please check it out and tell me if it is okay.

**Comment by Ananya54321** [comment]
I have a doubt. Wouldn't it be better to redirect users to "https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Readme/Contributing.md" i.e., the contributing file directly?

**Comment by sanjay-kv** [comment]
https://github.com/Recode-Hive/Stackoverflow-Analysis/tree/main/Readme this would be the right location

**Comment by Ananya54321** [comment]
okayy!
