### ISSUE TITLE
[FEATURE] references/links to external resources to support download & using the repository

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#13]
### Description
Reference to external links to resources, to support the new user to download and use the repository as the data source is more than 500MB and Github has limitations for the large files. 

- [ ] Fetching the data source should be clearly mentioned.

**Comment by Sakshamag21** [comment]
Hi @JiyaGupta-cs  I would like to work on this issue for GSSOC'24 and all other issues as well. I am attaching my resume for reference of my work. [https://drive.google.com/file/d/1HgwfbdcNRL-e9LTkqVRpu3XAbmMK8faf/view?usp=sharing](resume) . My discord id:- 210906_sakshamagarwal

**Comment by sanjay-kv** [comment]
Dont start right now, start after may 10

**Comment by sanjay-kv** [comment]
You can start working on it i have added the labels. @Sakshamag21

**Comment by JVENKATAPHANISAI** [comment]
Hello @sanjay-kv . I would like to work on this issue for GSSOC'24. 
My discord I'd : "namecontributor_36700_96512"
I want to explain my way of approach for this issue : 
1) To resolve the issue of hosting large data files on GitHub, I can consider using external services those are designed for handling large files.(for this I have to make changes and updates in README file)
2) Hosting data on external storages.
3) Providing clear instructions and explaining how to use them.
4)Offering support if any issues encountered.
5) keeping files updated.

Hoping for the positive consideration.
regards,
Contributor | Phanisai.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis.
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by mansi104-ai** [comment]
Is this issue still open?
I would like to work on it , if the issue hasn't been resolved yet

My discord Id: Mansi_1004
