### ISSUE TITLE
Refactor Streamlit App for Better Performance and Maintainability

### ISSUE THREAD

**Issue by say-het** [Recode-Hive/Stackoverflow-Analysis#137]
**Describe the bug**
The current Streamlit app implementation can be optimized for better performance, readability, and maintainability. The code contains repetitive elements and lacks modularity. This issue aims to refactor the codebase to address these concerns.

**Proposed Changes:**

**Modularize Code**: Break down the code into smaller, reusable functions.
**Refactor Repetitive Code**: Use functions to handle repetitive tasks.
**Improve Readability**: Add comments and organize the code into logical sections.
**Dynamic Data Loading**: Load data based on the selected year to optimize performance.
**Enhance Visuals**: Use consistent formatting and better layout management.
**Add Error Handling**: Ensure the code handles potential errors gracefully.

**Steps to Implement:**

Define functions for loading data, applying CSS, displaying analysis text, and visualizations.
Refactor the main script to use these functions.
Test the refactored code to ensure functionality remains intact.
Review and update documentation/comments for clarity.

**Benefits:**

Improved performance by dynamically loading data.
Enhanced code readability and maintainability.
Simplified future development and feature additions.

Hey! @sanjay-kv I have already made required changes. Assign me this Issue under GSSoC so I can raise a PR.

Little about me : I am experienced contributor as I have completed Hacktoberfest-2020 and Hactoberfest-2023 successfully.

**Comment by sanjay-kv** [comment]
https://github.com/Recode-Hive/Stackoverflow-Analysis/tree/main/streamlit

@say-het I really liked the explanation, i see @leena @NIKITA320495 has already implemented it, maybe you can help in further improvements and host it on streamlit cloud or something. Whats your thoughts.

**Comment by akashlogics** [comment]
I understood the issue. Please assign to me.
