### ISSUE TITLE
Enhance Data Visualization and Interactive Dashboard

### ISSUE THREAD

**Issue by Vikranth3140** [Recode-Hive/Stackoverflow-Analysis#141]
## Description:
The current visualizations are static and could be improved by making them interactive, providing a more insightful and engaging user experience. Implementing an interactive dashboard with tools like Plotly and Dash can achieve this.

## Tasks:
Install and configure Plotly and Dash.
Create interactive visualizations for key insights.
Integrate the visualizations into a dashboard.

**Comment by sanjay-kv** [comment]
currently we are heading towards streamlit app, I will tag you once we were able to host . you can proceed visualisation there, I'm closing the issue for time being.
