### ISSUE TITLE
[Documentation Update]: A new documentation containing the readme.md for the working webpage 

### ISSUE THREAD

**Issue by NIKITA320495** [Recode-Hive/Stackoverflow-Analysis#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

there should be a readme file for the working webpage also . which should countain all the description  of webpage.

### Suggested Change

firstly it should contain the solution we provided in our webpage , decsription of all the functions and their working , the visualization templates, the datasets we have used, and the libraries we have used . secondly it should contain all the commands that how should anyone proceed with starting from how to clone this repo and how to run the webpage.

### Rationale

it would help one to understand the whole webpage

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by NIKITA320495** [comment]
@sanjay-kv please assign this issue to @Leena2403

**Comment by sanjay-kv** [comment]
can u tell leena to comment here not able to assign her  @Leena2403

**Comment by Leena2403** [comment]
Yes sir, I am here. Please assign me as well. @sanjay-kv
