### ISSUE TITLE
Performing EDA and building an dynamic dashboard using Power BI[Feature Request]: 

### ISSUE THREAD

**Issue by jeet-Abhi123** [Recode-Hive/Stackoverflow-Analysis#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will be working on survey_results_public_2018.csv dataset. I will be performing EDA on 'Country', 'Comptotal', 'JobSatisfaction', 'DevType', 'YearsCode', 'Employment', 'Respondent'. 
Handling the missing values of the dataset using some techniques like mode, random sample imputation etc. 
Doing EDA on the columns like : 
1) Bar plot showing the different types of developers (e.g., web developer, mobile developer, data scientist) and their counts.
2) Job Satisfaction of the people based on the different countries.
3) Pie chart or bar plot showing the employment status of respondents.

And finally building an dynamic dashboard using Power BI which will be having more meaningful insights of the dataset.

### Use Case

1) Identify trends and patterns within the developer community.
Example: Companies can use insights on the most common developer roles, popular programming languages, and desired technologies to align their product development and marketing strategies.

2) Tailor educational resources and training programs based on developer needs.
Example: Educational institutions and training providers can create courses focusing on the most sought-after skills and technologies identified in the dataset.

And there can be many use cases.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
How woudl you integrate powerbi to this. its complete tech stack isn't it?

**Comment by jeet-Abhi123** [comment]
I would handle missing values and do some basic EDA in colab and export that csv file and from that csv file I will import it in the Power BI. I know we can do transformation in Power BI  but I found doing it in notebook more understandable and easy.

**Comment by jeet-Abhi123** [comment]
@sanjay-kv  Why you have closed this issue? May I know the reason?
You assigned me and closed it.
