### ISSUE TITLE
[Bug]: Streamlit app

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://stackoverflow-analysis.streamlit.app/

I have hosted stream lit app the above is the link but there is some error in the deployment which points to the code base. 
Can you look into it. @NIKITA320495 @leena
ModuleNotFoundError: No module named 'pyco

### Add ScreenShots

![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/30715153/6a4ad4ed-2f32-467a-81a2-4efc24acf04e)

![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/30715153/e782f27f-4246-4c07-9a9e-62fa5b0956c3)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC contributor
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by NIKITA320495** [comment]
@sanjay-kv sir have you installed pycountry module using pip install pycountry in cmd?

**Comment by Leena2403** [comment]
@sanjay-kv Sir, the module needs to be installed first. But if the error occurs, we'll definitely look into it. 

Also, please refer to me as @Leena2403 as my real username, currently you're referring to some other @Leena from Montreal, so I am unable to receive your notifications.

**Comment by sanjay-kv** [comment]
Thanks for highlighting.
