### ISSUE TITLE
[Feature Request]: Add KMeans for prediction and other algorithms and ensemble results

### ISSUE THREAD

**Issue by sanskritiagr** [Recode-Hive/Stackoverflow-Analysis#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Sometimes KMeans give better results in datasets like these. I want to try it out. I would also like to run few more algorithms. Then also ensemble results.

### Use Case

It can help us give better accuracy and hence better results for users.

### Benefits

It can help us give better accuracy.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanskritiagr** [comment]
I have submitted a pull request. Can you please check.

**Comment by sanskritiagr** [comment]
@sanjay-kv

**Comment by sanskritiagr** [comment]
Thank you. Its done.

**Comment by sanskritiagr** [comment]
Does the issue needs to be closed since its done? And also how will it be reflected on the leaderboard for GsSoc'24.

**Comment by sanjay-kv** [comment]
it need to be closed. It's a simple Node app that runs a cron job & fetches via GitHub octokit api/sdk and update the leaderboard
