### ISSUE TITLE
[Documentation Update]: License Issue

### ISSUE THREAD

**Issue by say-het** [Recode-Hive/Stackoverflow-Analysis#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The issue is that it shows no license available
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/71073587/750809e8-e1f3-42a7-a1db-b72a9d7cd409)

### Suggested Change

I have changed the markdown file.
Hey! @sanjay-kv please assign me this issue so that i can raise a PR.

Thanks.

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
can u add more relevant badges as well?
