### ISSUE TITLE
[Feature Request]: Popularity of AI Tools Over Time and AI skill demand analysis.

### ISSUE THREAD

**Issue by Navyazitya** [Recode-Hive/Stackoverflow-Analysis#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Tracking the trends in the popularity of different AI tools over time and also analyze the slow changes and to develop a predictive model to forecast future popularity trends.

### Use Case

This feature would be beneficial to current education pursuing students or job seeking professionals where one can know the current trend analysis, and take valuable data driven decisions and community insights for choosing the good profession or domain.

### Benefits

This is beneficial for the project for dropping insights related to trend prediction ,career advancement and educational insights.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Aayushi1111** [comment]
hey i would  like to contribute ,can u assign me the issue

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model.
