### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by 23wh1a1277** [Recode-Hive/Stackoverflow-Analysis#193]
### Name

Trupti Agrawal

### Discord Username (if applicable)

Truptiagrawal#2658

### Additional Context

To start my open source code journey. I'm very much excited to do so. Thank you for the opportunity.

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Recode-Hive/people<br><br>
