### ISSUE TITLE
[Feature Request]: Find out the most preferred way to learn coding for different age groups

### ISSUE THREAD

**Issue by merciajeno** [Recode-Hive/Stackoverflow-Analysis#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Perform data analysis and find the most preferred way of learning to code for different age groups.

### Use Case

This feature enhancement will be helpful for the beginners of a particular age group who are new to tech and are confused on how and where to begin.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by merciajeno** [comment]
@sanjay-kv , I am willing to work on this feature. Can you assign me ?

**Comment by Srijansarkar17** [comment]
Hey @sanjay-kv i would like to work on this issue. Can you assign it to me?

**Comment by merciajeno** [comment]
@sanjay-kv , Can you review the code and let me know if I have to make any changes?

**Comment by sanjay-kv** [comment]
Sure will do in a day .
