### ISSUE TITLE
[Bug]: Remove system and IDE files

### ISSUE THREAD

**Issue by Varshni11** [Recode-Hive/Stackoverflow-Analysis#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Found .DS_Store, .vscode and pycache in the repo which can be removed so that it can decrease file size and as it is unnecessary.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by GUNJESH843** [comment]
hey @sanjay-kv please assign the issue to me.
