### ISSUE TITLE
Perform EDA on data

### ISSUE THREAD

**Issue by Kyouma45** [Recode-Hive/Stackoverflow-Analysis#27]
**Describe the solution you'd like**
I would like to perform EDA on the given dataset.

**Describe alternatives you've considered**

**Additional context**
Performing the EDA might help find more patterns from the data increasing model's performance.

What problem is this feature trying to solve?
It will increase model's performance and accuracy.

How do we know when the feature is complete?
Results of EDA will be shown in the form of graps.

Please assign this task to me.

**Comment by sanjay-kv** [comment]
I will assign the task after program launch which is 7pm IST tomorrow.

**Comment by pryang007** [comment]
Hello Sir @sanjay-kv , I want to work on this issue as currently I'm working on ML projects and I'm in hand with Pandas, Seaborn, Numpy, matplotlib libraries of Python.
I'm so much eager to work on this, waiting eagerly for your reply.

**Comment by Harshu467** [comment]
I want to work on this issue , please assign this to me

**Comment by deepti-50** [comment]
I want to work on this issue,please reassign it to me

**Comment by ShreyaAwasekar** [comment]
I want to work on this issue, please assign it to me.

**Comment by Kyouma45** [comment]
> I will assign the task after program launch which is 7pm IST tomorrow.

Hello Sir @sanjay-kv, as you mentioned before, please assign this issue to me. This is my expertise and I have already started working on it

**Comment by ananya39mehta** [comment]
Hello sir, I would like to work on this part.

**Comment by Navyazitya** [comment]
hello @sanjay-kv sir, I would like to work on this sir and as I performed EDA on other data sets as well I think I can do this sir.
Sir could please assign this to me and update the level of it.

**Comment by samriddh-i** [comment]
hello @sanjay-kv sir, i would like to work on this issue please assign it to me

**Comment by sanjay-kv** [comment]
anyone can work and send me a pull request to me. I will review and merge the best one.

**Comment by Kirti-Pant** [comment]
hello @sanjay-kv , please assign this issue to me?

**Comment by SanskarShrivastava** [comment]
I want to contribute to this isssue

**Comment by SwarnenduJUIT** [comment]
I want to contribute assign me this issue

**Comment by Devanik21** [comment]
Thanks a lot 😊

**Comment by Devanik21** [comment]
Thanks a lot 😊

**Comment by sanjay-kv** [comment]
I can only assign upto 10 people at the moment, you can create a new issue which you feel like to add. I will add the label and you can work on it

**Comment by swastim01** [comment]
Please assign this issue to me.

**Comment by shubhamnakum** [comment]
@sanjay-kv sir i want to work on this issue please allow me to work on it.

**Comment by Navyazitya** [comment]
Sir @sanjay-kv  should I start working on this sir.

**Comment by Pranali3103** [comment]
I am GSSOC'24 contributor and I's like to work on this issue please assign it to me

**Comment by saisri0102** [comment]
@sanjay-kv I am GSSOC'24 contributor and want to work on this issue. Can I go ahead and work on issue that's not assigned to me? Can I also take up issues if it's already assigned to someone else?

**Comment by Navyazitya** [comment]
Sir, when should we stop working on a particular issue and go for the next issue sir.. Like I worked on this like I cleaned and also removed he outliers different univariate and bivariate visualizations and now I am doing correlation analysis.. And I feel this would be good enough EDA sir.. what should I do..?

**Comment by SuhaniStark** [comment]
Under GSSoC'24, I would like to work on this issue, please assign it to me.

**Comment by Navyazitya** [comment]
Sir.. I sent a PR regarding to this issue 2days ago sir.. please check it
once sir.. I actually included all the code in one ipynb only.. I sent it
2days back.. could you please check that and merge it.. please sir
