### ISSUE TITLE
[Feature Request]: Add google translate feature

### ISSUE THREAD

**Issue by MuraliDharan7** [Recode-Hive/Stackoverflow-Analysis#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add google translate feature which translate the entire page with the given language.

### Use Case

This would help the users to look out the page with their language.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
Not related issue
