### ISSUE TITLE
[Feature Request]: Predicting Salaries Using RandomForestRegressor

### ISSUE THREAD

**Issue by nidhivmehta** [Recode-Hive/Stackoverflow-Analysis#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a feature that utilizes a RandomForestRegressor model to predict yearly compensation (ConvertedCompYearly) based on features extracted from 'Survey_results_sample_2023.csv' dataset. 
The features for prediction includes:

YearsCode: Numeric representation of years of coding experience, handling non-numeric values like 'Less than 1 year' and 'More than 50 years'.
EdLevel: Categorical feature indicating the highest level of education completed by respondents.
Country: Categorical feature denoting the country of residence of the respondents.

### Use Case

This predictive model serves as a tool to estimate yearly compensation for developers. This capability is useful for both individual developers and hiring managers who are seeking for insights into salary expectations across different demographics.

### Benefits

Community and Industry Relevance

Below, I have attached the output of the input
![salary](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/107789227/ec49fcc7-a78a-4b4c-b009-469b278acf31)

1. The model predicts a yearly compensation of $43822 for someone with 5 years of coding experience, a Bachelor’s degree from the United States.
2. The model predicts a yearly compensation of $79370 for someone with 10 years of coding experience, a Master’s degree from Canada.
3. The model predicts a yearly compensation of $33485 for someone with 3 years of coding experience, some college/university study without earning a degree from Germany.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
To highlight we dont need different folder or separate file for this analysis do it in the main file.
