### ISSUE TITLE
Quirky CSS icon

### ISSUE THREAD

**Issue by GitNinja-bcd** [Recode-Hive/Stackoverflow-Analysis#29]
**Describe the bug**
CSS icon appears misaligned.

**To Reproduce**
1. Go to the Screenshot part of that repository.
3. Scroll down to 'Most Used Languages'.
4. Look at CSS icon which appears misaligned.
![Screenshot 2024-05-10 234432](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/158538244/22f48d78-40b7-420d-add5-55bd5d61bc24)

**Comment by sanjay-kv** [comment]
Hi @GitNinja-bcd are ou referring to this Stackoverflow project, we don't use CSS, could you check that again

**Comment by codebreaker3008** [comment]
@sanjay-kv  could you assign this to me ?

**Comment by GitNinja-bcd** [comment]
Can I solve this issue? 
Kindly assign me I will definitely solve it.

**Comment by GitNinja-bcd** [comment]
@sanjay-kv  my issue is related to gitglance project.

**Comment by sanjay-kv** [comment]
@GitNinja-bcd I still didn't get you . if its related to some other repository you should ask here. i don't see its relevant to current repo. And gitglance project is not managed by me, so I wont be able to assign

**Comment by codebreaker3008** [comment]
@sanjay-kv  could you assign this to me ?

**Comment by GitNinja-bcd** [comment]
@sanjay-kv yes, this is related to another repository. 
I accidentally raised the issue here. I can understand that you can't assign it. Thank you.
