### ISSUE TITLE
[Feature Request]: Enhancement of the website 

### ISSUE THREAD

**Issue by CoderGirl2844** [Recode-Hive/Stackoverflow-Analysis#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the text in white boxes is not visible so I will change the interface according to website theme

https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/155231566/432d06c8-d4eb-4961-bd5f-6935c09c1496

 

### Use Case

this feature would improve the look of website.
please assign this issue to me.
additionally, I would like to add items in Nav bar of the website

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by sanjay-kv** [comment]
I have to look at this, because there is another person working on the similar issue

**Comment by CoderGirl2844** [comment]
Is this issue solved? If not I would like to work on it

**Comment by sanjay-kv** [comment]
yes this has been done, you can work on the 
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/30715153/1e4577e6-0e66-42e0-b781-2b3a86c8e837)
adding more years code is available in ipynb file.create a new issue if you would like to work
