### ISSUE TITLE
Update Readme page 

### ISSUE THREAD

**Issue by Sibam-Paul** [Recode-Hive/Stackoverflow-Analysis#30]
### Saw the link must be mentioned in new line 

**Picture reference**
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/158052549/af0036fa-014a-4577-8f86-36d29ad9752c)

Hey Can I fix this 
_Please assign it to me under GSSOC'24_

**Comment by sanjay-kv** [comment]
Assigned to you @Sibam-Paul

**Comment by DevNandini02** [comment]
**Spelling error in the word higher**

![issue](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/124669890/0eb7f2df-2076-4cf0-9238-eb43b94637cf)

I can fix it.
Please assign this to me.

**Comment by DevNandini02** [comment]
**I can fix it.
Please assign it to me.**

![issue2](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/124669890/d694a7bc-a409-4f90-b38a-cdf6199df896)

**Comment by singhpratibha98** [comment]
Please assign this task to me . I want to fix this documentation.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by Sibam-Paul** [comment]
@sanjay-kv h is already present in the main branch
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/158052549/68e526c4-ec72-4786-bf39-4645cac6006c)

**Comment by sanjay-kv** [comment]
tag @Sibam-Paul  @DevNandini02 if you want to work together

**Comment by DevNandini02** [comment]
@sanjay-kv sir please add the level to this issue.

**Comment by sanjay-kv** [comment]
@DevNandini02 This is a minior issue cant provide level1
