### ISSUE TITLE
Add Heat_Map for Data Analysis

### ISSUE THREAD

**Issue by Saksh8** [Recode-Hive/Stackoverflow-Analysis#35]
I want to depict data in the form of a heat map to visualize the data of different columns such as employment, job status, language, language desired, ethnicity, etc.

**Comment by thakurboy004** [comment]
Hi I am Abhishek, I am a contributor to GSSoC'24 and would like to contribute to this issue, can you please assign this issue to me

**Comment by Nidhi20-7** [comment]
Hi I am Nidhi ,I have good knowledge about data visualization ,can you please assign this issue to me?

**Comment by varsha-ky12** [comment]
Hi there, i too would like to work on heat map visualizations .

**Comment by Darshants6364** [comment]
Hi I am Dashan T S, I am a contributor to GSSoC'24 and would like to contribute to this issue.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by thakurboy004** [comment]
> Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days Also if you would like to work on more issue create a new issue and I will create label and assign you.

Hi @sanjay-kv I was assigned to this issue and then unassigned within two hours can explain why?

**Comment by why-Radhika** [comment]
Hey. I have experience in working on data analytics. I see the issue has been assigned 3 weeks ago and no work has been done yet. So can you please assign this issue to me.

**Comment by sanjay-kv** [comment]
This issue PR is already done
