### ISSUE TITLE
SCRAPE DATA FROM OTHER AVAILABLE PLATFORM TO ENHANCE ANALYSIS  [ML/ Scraping]  GSSOC 24

### ISSUE THREAD

**Issue by yusuf-khaan** [Recode-Hive/Stackoverflow-Analysis#36]
**Is your feature request related to a problem? Please describe.**
As we are currently using the data using the stackanalysis for past 3 YEARS our scope is limited and i would like to enhance our scope

**Describe the solution you'd like**
I would like to develope algorithm to Scrape data from other platform and create a REFINED DATA STRUCTURE as well as increase our scope and have a broader vision

**Describe alternatives you've considered**
There are various platform avaialable including stackoverflow like GLASSDOOR etc

What problem is this feature trying to solve?
This Feature will give a better scope and range and wider data to enhance our analysis on data
 
How do we know when the feature is complete?
I will notify the admin when the feature is complete, it should not take more than 1-2 weeks to completely merge the feature

**Comment by yusuf-khaan** [comment]
Thanks for assigning this issue to me @sanjay-kv

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.
