### ISSUE TITLE
Another Readme File Bug 

### ISSUE THREAD

**Issue by Sibam-Paul** [Recode-Hive/Stackoverflow-Analysis#39]
**Is your feature request related to a problem? Please describe.**
_Missing the "H" in the readme ._

**Describe the solution you'd like**
Will change it.

**Additional context**
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/158052549/7324d60e-202e-49a0-a9d3-20b5f0265f24)

_Please assign me this so that I can contibute in it_

**Comment by Sibam-Paul** [comment]
@sanjay-kv I have made the necessary changes see
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/158052549/6bff397a-054e-4a37-8be1-9ae413264a5f)

And I think It was merged into the main 
please check 

Thank you

**Comment by SAURABH-CHAMOLI** [comment]
can you assign the label to it.

**Comment by Sibam-Paul** [comment]
@sanjay-kv Can u please assign the level1 to it

**Comment by sanjay-kv** [comment]
this is minor issue cant assign level 1
