### ISSUE TITLE
Adding Catboost Regressor

### ISSUE THREAD

**Issue by Maryam-Sikander** [Recode-Hive/Stackoverflow-Analysis#41]
I think we should train the model using the CatBoost Regressor. Given the data's nature, I believe it will give optimal results with CatBoost.

**Comment by sanjay-kv** [comment]
Hi @Maryam-Sikander i assigned you this issue. Please work on it.

**Comment by SwarnenduJUIT** [comment]
hi @sanjay-kv  I too think cat boosting algorithm could be used  .assign me the issue plz
