### ISSUE TITLE
Model performance under Gradient boosting

### ISSUE THREAD

**Issue by SwarnenduJUIT** [Recode-Hive/Stackoverflow-Analysis#43]
**Is your feature request related to a problem? Please describe.**
Checking for the best algorithms among the various bagging and boosting techniques such as gradient boosting,XG boosting etc..

**Describe the solution you'd like**
Gradient boosting trees can be more accurate than random forest because we can train them to correct each others errors.Aim to decrease bias  and model will be weighted according  to their performance.

**Describe alternatives you've considered**
Alternatively ,  i would more for  XG boost to do the same as gradient boosting

.

What problem is this feature trying to solve?
we might check the dataset with boosting techniques to reach a conclusion.

How do we know when the feature is complete?
simply we compare for model accuracy than previous random forest model and current gradient boosting  model.

**Comment by SwarnenduJUIT** [comment]
@sanjay-kv  kindly assign me this issue and i would go through the boosting technique for [FEATURE] Add New ML Algorithms #8

**Comment by sanjay-kv** [comment]
assigned to u @SwarnenduJUIT

**Comment by MJakash** [comment]
Hey bhaiya ! i am data science and machine learning enthusiast.I have worked on predictive modelling. After seeing this issue i want to work on this issue.If possible then kindly assign this issue to me.

**Comment by Pranali3103** [comment]
Hi @sanjay-kv , I would like to work on this issue , please assign me this issue.
