### ISSUE TITLE
Country wise clustering for improved tech-market analysis. 

### ISSUE THREAD

**Issue by Leena2403** [Recode-Hive/Stackoverflow-Analysis#48]
**Is your feature request related to a problem? Please describe.**

People from different country have different needs and goals in life. Whereas someone from poorer country will want to work with the tech-stack that generates highest salary at the expense of job-satisfaction, someone from wealthier place will emphasise job-satisfaction, and less working hours. 

Providing a more personalised analysis of tech market is needed.

**Describe the solution you'd like**

***Clustering similar countries together to perform ML model. It generates the relevant language(s) based on the user inputs along with the probability and proper visualisations***

**Additional context**
I'm a GSSoC'24 Contributor, with the experience in Machine Learning. Kindly assign the issue to me, I agree to follow this project's Code of Conduct.

**Comment by Avishek8136** [comment]
I would like to contribute on this and use unsupervised learning algorithms to get best results. Assign this to me

**Comment by Kazasunitha** [comment]
I like to contribute this by using clustering algorithms which is unsupervised. I want to deal this issue. Please label GSSoC'24 and Assign this for me

**Comment by Leena2403** [comment]
@sanjay-kv sir, please assign @NIKITA320495  as well.

**Comment by sanjay-kv** [comment]
Done

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model.
