### ISSUE TITLE
Make Issue template more visually appealing. 

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#51]
**Describe the Feature you want to end**

Currently, the issue template for this repo seems to be basic also it is less visually appealing.👇

![Screenshot 2023-06-12 at 02-10-25 New Issue · pranjay-poddar_Dev-Geeks](https://github.com/pranjay-poddar/Dev-Geeks/assets/115932772/3dfb3eb8-5295-4cbb-90f7-d93f6fad7e6c)

Changes I will make 

![Screenshot 2023-06-11 at 01-12-48 New Issue · dakshsinghrathore_htmltut](https://github.com/MonalikaPatnaik/UMatter/assets/115932772/24e42af3-1b4f-4d75-9f29-805e50d63fd5)

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**
**Will add issue forms to the respective issues to make it easier for the contributor to raise it.**
Here is an example of how a ***Bug Issue Form*** will look like 👇

![Screenshot 2023-06-11 at 01-15-06 New Issue · dakshsinghrathore_htmltut](https://github.com/MonalikaPatnaik/UMatter/assets/115932772/d6d11ddf-3874-4229-b9a8-6087c99e10e2)

**Comment by aditi-sharma-2004** [comment]
Hey! I would love to work on this issue. Please assign it to me under GSSOC'24. @sanjay-kv

**Comment by RangojuNandini** [comment]
I would like to work on this issue under GSSoC 2024.Please assign this issue to me.

**Comment by TonyStark-47** [comment]
Hey, @sanjay-kv, I have raised a pull request and updated the information as you requested.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis.
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by TonyStark-47** [comment]
hey @sanjay-kv, 1 week has been passed.

**Comment by sanjay-kv** [comment]
Thanks for mentioning. I will add the same.

**Comment by TonyStark-47** [comment]
Yes, it's here: #57
