### ISSUE TITLE
Add 2021,2022,2023 Schema and Sample Dataset

### ISSUE THREAD

**Issue by code-with-aneesh** [Recode-Hive/Stackoverflow-Analysis#55]

**Comment by sanjay-kv** [comment]
The Sample dataset is already available on the repo: https://github.com/Recode-Hive/Stackoverflow-Analysis/tree/main/Data

**Comment by code-with-aneesh** [comment]
For 21,22,23 it is not present.
I wanted to add that

**Comment by sanjay-kv** [comment]
Alright @code-with-aneesh I will assign this issue to you
