### ISSUE TITLE
Impute missing value and Normalization of the skewed Csv data.

### ISSUE THREAD

**Issue by akv2011** [Recode-Hive/Stackoverflow-Analysis#58]
**Describe the bug**
Hi I would  like to 
Hi @sanjay-kv  I would like to Normalize skewed value and Perform EDA so that its' fit for model training.
I plan to to go through all the data sets .

**Comment by sanjay-kv** [comment]
Could you let me know where is the bug with a ss. so I can more understand in detail the issue you try to solve.

**Comment by akv2011** [comment]
Hi @sanjay-kv  I am facing the following isue in the survey_results_sample_2018.csv Dataset 
![Screenshot from 2024-05-12 19-42-51](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/137097109/73eca86e-3302-4222-a30b-50be816d4568)

There are bad lines in the dataset Would like to solve them Istead of just ignoring them 

Also There are  NA values in the datatset will like to Impute Them so that model can parse Them .
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/137097109/2046a2bd-a33f-4fa5-bc9a-1465a86295ab)

**Comment by sanjay-kv** [comment]
@akv2011  Assigned to you.

**Comment by akv2011** [comment]
Thank you will work on it pronto ...and raise pull for review .

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model.
