### ISSUE TITLE
Investigate participation rates based on ethnicity and differences in income between men and women.

### ISSUE THREAD

**Issue by Yodha-Sudarsi** [Recode-Hive/Stackoverflow-Analysis#61]
**Is your feature request related to a problem? Please describe.**
I would like to work on Investigating participation rates based on ethnicity and differences in income between men and women.

**Describe the solution you'd like**
I would select the required features for this problem and use data visualization technique to solve this feature.

**Describe alternatives you've considered**
Another alternative is to simply display the numbers instead of data visualization technique.

**Additional context**
This problem was listed in the project goals, so decided to hop and work on this...

What problem is this feature trying to solve?
Investigate participation rates based on ethnicity and differences in income between men and women.

How do we know when the feature is complete?
I will send a PR within 3 days.

**Comment by SuhaniStark** [comment]
Under GSSoC'24, I would like to work on this issue, please assign it to me.

**Comment by Yodha-Sudarsi** [comment]
@SuhaniStark, I wanted to let you know that I've finished the task and submitted a pull request. However, if you're interested, we can collaborate further on  #94 .

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model.
