### ISSUE TITLE
Improve the UI of Login and Signup page and integrate social media platforms.

### ISSUE THREAD

**Issue by Chelsea67jain** [Recode-Hive/Stackoverflow-Analysis#70]
I observed that the UI of the login and signup page is too simple. It can be improved and also I can add form validations to avoid error 404.
![Screenshot (495)](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/100270122/72c38180-6374-412a-910c-d3697e5f9c70)
![Screenshot (494)](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/100270122/5adce1d1-5567-4201-aab4-6b0c80886077)

Expected behavior
I accepted to see the username on the navbar but got an error 404.

Screenshots:

**Desktop (please complete the following information):**
 - OS [Windows]
 - Browser [Microsoft bing]

I have worked previously on an e-commerce website. I can resolve this issue.
@mohitparmar1 can you assign me this task under @GSS0C24.

**Comment by sanjay-kv** [comment]
This is different repository so Closing the issue @Chelsea67jain
