### ISSUE TITLE
Filter genuine user for subscription

### ISSUE THREAD

**Issue by pankaj-bind** [Recode-Hive/Stackoverflow-Analysis#71]
**Is your feature request related to a problem? Please describe.**
In your application anyone can subscribe using **temporary or disposable email**.

**Describe the solution you'd like**
I will add a feature so that no one could use **temporary or disposable email** for subscription.

What problem is this feature trying to solve?
It will allow only genuine users.
It will help to avoid any bot.

How do we know when the feature is complete?
I will create a PR.

Assign me this work under GSSoC24, I will implement it.

**Comment by sanjay-kv** [comment]
This is not relevant repo. @pankaj-bind
