### ISSUE TITLE
Analysis on year 2020 dataset 

### ISSUE THREAD

**Issue by avii-07** [Recode-Hive/Stackoverflow-Analysis#76]
Hi @sanjay-kv 
I am Avi, one of the contributors to GSSOC'24.  I would like to do an analysis on the 2020 year dataset. I will answer the questions like most used language, what new tools are needed to learn for the future etc. I will also do the analysis on the age, gender, country, job satisfaction of the people, employment, Overtime, number of years doing coding etc. 

Hoping for a positive response. 

With warm regards,
Avi Mittal

**Comment by sanjay-kv** [comment]
Hi @avii-07 This is already addressed in the file

**Comment by Nehakohli123** [comment]
Hi @sanjay-kv 
 I am Neha . I would like to do analysis for the 2020 dataset and would like to visualise the dataset through many charts that can forecast for the upcoming year as well using Power BI.
Hoping for the positive response.

With warm regards,
Neha Kohli

**Comment by okaditya84** [comment]
> Hi @sanjay-kv I am Neha . I would like to do analysis for the 2020 dataset and would like to visualise the dataset through many charts that can forecast for the upcoming year as well using Power BI. Hoping for the positive response.
> 
> With warm regards, Neha Kohli

This issue is already solved. Give more insights on which charts will be helpful and why?
