### ISSUE TITLE
Change in trends of the market due to Recession and the Pandemic 

### ISSUE THREAD

**Issue by chelsi-k** [Recode-Hive/Stackoverflow-Analysis#77]
Hi, I'd like to the analysis for the same data in the period 2021-2023 and compare it with the results found in the period 2018-2020 and analyze how the pandemic, the recession and the growth of AI has impacted the industry and it's people. 

I'm a GSSoC'24 Contributor, with experience in Machine Learning. Kindly assign the issue to me, I agree to follow this project's Code of Conduct.

**Comment by okaditya84** [comment]
> Hi, I'd like to the analysis for the same data in the period 2021-2023 and compare it with the results found in the period 2018-2020 and analyze how the pandemic, the recession and the growth of AI has impacted the industry and it's people.
> 
> I'm a GSSoC'24 Contributor, with experience in Machine Learning. Kindly assign the issue to me, I agree to follow this project's Code of Conduct.

Kindly give more insights and details.

**Comment by chelsi-k** [comment]
Hi, I forgot to push my changes, can you please assign this to me again. @sanjay-kv

**Comment by sanjay-kv** [comment]
its already assigned to you.
