### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by sanskritilabroo** [Recode-Hive/Stackoverflow-Analysis#79]
I noticed the README.files under documentation is incomplete for all categories. I would like to help by contributing to making these files detailed with all the info about the project and easy to understand. Some files are explained in other sections but not in the documentation section, would like to fix that as well by shifting them around so that everything is in one place.
Please assign me this issue under GSSOC'24 @sanjay-kv .

**Comment by sanjay-kv** [comment]
In terms of documentation its been addressed well in learn.md. If you see anything missing can highlight.

**Comment by shrawani21** [comment]
I also want to consolidate information from other sections and assign the task under GSSOC'24 to @sanjay-kv.
