### ISSUE TITLE
[FEATURE] Add New ML Algorithms

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#8]
Description: 
Given that the salary variable is a continuous variable, it would be right to apply regression models such as linear regression, random forest regressor, decision tree regressor, etc., but here we did apply classification models and reported classification accuracy, which seems a bit odd .

- [ ] Need to perform Linear Regression.
- [ ] Apply Random Forest Algorithm.
- [ ] Add Decision tree Regressor.

**Comment by Harshu467** [comment]
I want to work on this issue , please assign this to me

**Comment by ShreyaAwasekar** [comment]
I want to work on this issue , please assign this to me

**Comment by samriddh-i** [comment]
hello @sanjay-kv sir i would like to work on this issue. i have experience of machine learning algorithms i am confident i would be able to do the implementation correctly please assign it to me.

**Comment by Kirti-Pant** [comment]
Hello @sanjay-kv , I'd like to work on this issue please assign it to me under GSSoC'24

**Comment by diptarup794** [comment]
I want to work on this issue for GSSoc'24.Kndly assign it to me @sanjay-kv .

**Comment by Devanik21** [comment]
Please assign the task to me for GSSOC contribution!

**Comment by shaziaakhan** [comment]
Hi, please assign this to me
GSSOC 2024 Contributor

**Comment by SwarnenduJUIT** [comment]
hi @sanjay-kv  i want to contrtibute .Assign me this issue

**Comment by Devanik21** [comment]
Thanks a lot 😊

**Comment by Devanik21** [comment]
Thanks a lot 😊

**Comment by Devanik21** [comment]
Thanks a lot 😊

**Comment by MahimaRamireddy** [comment]
hello @sanjay-kv sir i would like to work on this issue sir. Given my background and expertise in machine learning, I would be enthusiastic about leading this effort. I believe I can implement it properly. Please assign this issue to me

**Comment by sanjay-kv** [comment]
Hi I assigned 10 people, try the PR, i will select the best one and merge. 
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by SwarnenduJUIT** [comment]
hi @sanjay-kv  I have basic experience in machine learning . I know how to train and test model on various ml algorithms. I am highly interested in the project kindly assign me the issue

**Comment by MJakash** [comment]
hello @sanjay-kv ! I have experience in model training as well as predictive modelling.I want to contribute to this issue.Kindly assign me this issue .

**Comment by MahimaRamireddy** [comment]
> hello @sanjay-kv sir i would like to work on this issue sir. Given my background and expertise in machine learning, I would be enthusiastic about leading this effort. I believe I can implement it properly. Please assign this issue to me

hello @sanjay.kv , may i  know why i have been unassigned from the issue?

**Comment by Amarta113** [comment]
> > hello @sanjay-kv sir i would like to work on this issue sir. Given my background and expertise in machine learning, I would be enthusiastic about leading this effort. I believe I can implement it properly. Please assign this issue to me
> 
> hello @sanjay-kv , may i know why i have been unassigned from the issue?

He mentioned that : 
Issue will be assigned to Only 1 person ...FCFS basis. Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

**Comment by aryaVishal1706** [comment]
hi @sanjay-kv this issue is assign to anyone??

**Comment by sanjay-kv** [comment]
yes @aryaVishal1706 you can see it over here
![image](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/30715153/7b021aa1-223b-4e46-9af4-ecc6c87a0687)

**Comment by Kirti-Pant** [comment]
@sanjay-kv  can I work on this project under GSSoC'24 ?
