### ISSUE TITLE
Important Update in readme.md

### ISSUE THREAD

**Issue by say-het** [Recode-Hive/Stackoverflow-Analysis#80]
**Describe the bug**

- I think that the CONTRIBUTING.md file is now updated.
- But still not updated in readme.md and Hyperlink to that file is also missing.

**Expected behavior**
 - I want a nice link in that so that new Contributors can Directly access Contributing Guidelines

Please @sanjay-kv assign me this issue so that I can raise a PR.

Little about me : I am experienced contributor as I have completed both _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by say-het** [comment]
Hey @sanjay-kv I have raised a PR.
Kindly, review it and merge it.

**Comment by 21atha** [comment]
Sir @sanjay-kv ,I would like to work on this feature , please assign it to me.

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.
