### ISSUE TITLE
Job preparation analysis

### ISSUE THREAD

**Issue by Navyazitya** [Recode-Hive/Stackoverflow-Analysis#82]
**Is your feature request related to a problem? Please describe.**
Yes, the present code is only focusing on few questions . We can answer many more questions using the dataset.

**Describe the solution you'd like**
I want answer the questions like Remote Work Preference vs. Salary,  salary of a particular domain language in the future, Preferred Development Tools vs. Salary, Performance Ratings vs. Salary and so on by visualizations and different problems.

**Describe alternatives you've considered**
Apart from visualizations I even want to train the model for the main questions to be answered as well.

**Additional context**
I would like to make amazing visualizations and models for the analysis. I think I am good at visualizing and can actually draw an analysis or conclusion for that answers.

What problem is this feature trying to solve?
This feature would solve  job preparation analysis like we can conclude what all should we do to get a high paying job.

How do we know when the feature is complete?
As soon as I answer a particular question I will raise a pull request and I will also intimate If I am done with the issue. Please do assign me this sir.

**Comment by shrawani21** [comment]
In addition, I possess strong skills in creating compelling visualizations and models for analysis. I'm confident in my ability to translate data into meaningful insights and draw conclusions effectively.

**Comment by Pranali3103** [comment]
Hi @Navyazitya , @sanjay-kv , I would like to work on this issue , can you please assign me this.

**Comment by Navyazitya** [comment]
Sir @sanjay-kv ... This is done.. Like I made all the analysis and visualizations with all the conclusions that are needed ... Is this issue done or should I do anything else sir..

**Comment by sanjay-kv** [comment]
PR It

**Comment by Navyazitya** [comment]
I already raised and you approved it as well sir.. @sanjay-kv
