### ISSUE TITLE
Implementing SVM's for Job Satisfaction Decision

### ISSUE THREAD

**Issue by sanskritilabroo** [Recode-Hive/Stackoverflow-Analysis#83]
I recommend implementation of another classification algorithm for Job Satisfaction using SVM's (Support Vector Machines) that can be benchmarked along with our pre-existing techniques.

Please assign me this task as a contributor under GSSOC'24 @sanjay-kv.

**Comment by DevNandini02** [comment]
@sanjay-kv sir i would like to work on it. Please assign me this task.
