### ISSUE TITLE
[Enhancement] Need a static webpage to represent the analysis of data

### ISSUE THREAD

**Issue by sanjay-kv** [Recode-Hive/Stackoverflow-Analysis#9]
### Description
Hey Everyone👋!
I think there should be static to the website for the overall analysis of the prediction and visualization rather than explaining via a Github Readme file.  The website can be achieved via any of the student developer packs or using Github Pages. 

- [ ] the Main page with Motivation to do the project
- [ ] Highlighting Main Visualisation
- [ ] About page about the developers and Maintainer details with GitHub Links.

**Comment by nishant0708** [comment]
hey can you assign it to me under Gssoc 2024

**Comment by Harshu467** [comment]
I want to work on this issue , please assign this to me

**Comment by DevNandini02** [comment]
Please assign the label.
I would like to work on this, please assign this to me.

**Comment by sanjay-kv** [comment]
@DevNandini02 @nawarajshah  I assigned the labels, you can start working.

**Comment by swastim01** [comment]
Is this issue sorted and closed? If not, can I contribute to this?

**Comment by NIKITA320495** [comment]
please assign this issue to me under GGSOC'24

**Comment by sanskritilabroo** [comment]
Hi, if help is still required, I would like to be assigned this issue as a contributor under GSSOC'24. @sanjay-kv

**Comment by nawarajshah** [comment]
I am working on this

**Comment by aryaVishal1706** [comment]
this issue is assign to anyone?
