### ISSUE TITLE
Adding Xgboost

### ISSUE THREAD

**Issue by SwarnenduJUIT** [Recode-Hive/Stackoverflow-Analysis#98]
**Is your feature request related to a problem? Please describe.**
XG boost algorithm might be helpful . XGboost is an boosting algorithm also known as EXTREME GRADIENT BOOSTING. It might be helpful and we can check the model accuracy to verify if it is more helpful than Random Forest or not.

**Describe the solution you'd like**
We will implement XGboost algorithm and compare the accuracy with the other models especially Random forest.

**Describe alternatives you've considered**
We can also move to Adaboost to check the accuracy for the model.

**Additional context**
Boosting models can be really helpful in some cases.

What problem is this feature trying to solve?
Helps to decide the best ml algorithm for the data.

How do we know when the feature is complete?
We will compare the accuracy and present it in the file itself.

**Comment by SwarnenduJUIT** [comment]
@sanjay-kv  assign me this issue and i will look forward to verify that if XGboost would be better option or not .

**Comment by Pranali3103** [comment]
Hi @sanjay-kv ,c an you please assign me this issue !!

**Comment by okaditya84** [comment]
> Hi @sanjay-kv ,c an you please assign me this issue !!

The issue is already assigned. Please brainstorm another.

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this
