### ISSUE TITLE
Bug on Random Forest Regressor for Job Satisfaction

### ISSUE THREAD

**Issue by sanskritilabroo** [Recode-Hive/Stackoverflow-Analysis#99]
**Describe the bug**
The random forest regressor is throwing an error because of a logical issue that is no.of splits are greater than no.of samples. For this logic to work, this model should only be applied on the dataset AFTER further splitting and not before.
I can fix this issue as a contributor under GSSOC'24 if assigned. @sanjay-kv 

**Screenshots**
<img width="715" alt="image" src="https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/86831838/9c9bfa79-9e3a-4f6b-a0a8-56e61086a46c">

**Comment by krati234** [comment]
assign this please

**Comment by akashlogics** [comment]
I am interested in solving this issue can you assign me, please

**Comment by aarushi-sahu23** [comment]
I would like to work on this issue, please assign me

**Comment by sanjay-kv** [comment]
Its already assigned if you want to collaborate reach out to assigned person

**Comment by sanskritilabroo** [comment]
Already fixed the bug with a pull request, hence issue is resolved.
